name: classify
description: A new Flutter application.

version: 1.0.0+14

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.12.4+1
  flutter_advanced_networkimage: ^0.4.15
  shared_preferences: ^0.5.2
  flutter_arhitecture_helper: ^0.4.3
  permission_handler: ^3.1.0
  # flutter_facebook_login: ^2.0.0
  firebase_core: ^0.4.0
  firebase_crashlytics: ^0.0.4+3
  firebase_messaging: ^5.0.0
  firebase_analytics: ^3.0.0
  firebase_auth: ^0.11.1
  firebase_storage: ^3.0.0
  cloud_firestore: ^0.11.0+2
  google_sign_in: ^4.0.1+3
  toast: ^0.1.4
  font_awesome_flutter: ^8.4.0
  cupertino_icons: ^0.1.2
  package_info: ^0.4.0+3
  flutter_page_indicator: ^0.0.3
  flutter_platform_widgets: ^0.10.0
  bubble_bottom_bar: ^1.2.0
  flutter_slidable: ^0.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.2

flutter:
  uses-material-design: true
  assets:
  - assets/images/icons/homeworkOrange.webp
  - assets/images/icons/homePurple.webp
  - assets/images/icons/profileGrey.webp
  - assets/images/icons/calendarGreen.webp
  - assets/images/profilePicture.webp
  - assets/icons/logo_icon.svg
  - assets/icons/google_icon.svg
  - assets/icons/mail_icon.svg
  - assets/icons/password_icon.svg
  - assets/icons/left_arrow.svg

  fonts:
      - family: GoogleSans
        fonts:
          - asset: assets/fonts/GoogleSans-Bold.ttf
          - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          - asset: assets/fonts/GoogleSans-Italic.ttf
          - asset: assets/fonts/GoogleSans-Medium.otf
          - asset: assets/fonts/GoogleSans-MediumItalic.otf
          - asset: assets/fonts/GoogleSans-Regular.ttf


