name: classify
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.12.0
  shared_preferences: ^0.5.2
  flutter_arhitecture_helper: ^0.3.9
  permission_handler: ^3.0.0

  firebase_core: ^0.4.0
  firebase_crashlytics: ^0.0.4+3
  firebase_messaging: ^5.0.0
  firebase_analytics: ^3.0.0
  toast: ^0.1.4
  flutter_advanced_networkimage: ^0.4.15
  cupertino_icons: ^0.1.2
  package_info: ^0.4.0+3
  flutter_page_indicator: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.2

flutter:
  uses-material-design: true
  assets:
  - assets/images/mojave1.webp
  - assets/images/mojave2.webp
  - assets/images/mojave3.webp

  fonts:
      - family: ProximaNova-Extrabld
        fonts:
          - asset: assets/fonts/ProximaNova-Extrabld.otf


